version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: github.com/onsi/ginkgo
    versions:
    - 1.15.1
    - 1.15.2
    - 1.16.0
  - dependency-name: github.com/gonvenience/bunt
    versions:
    - 1.3.2
