---
language: go
go:
- 1.12.x

install:
- curl -fsL https://ibm.biz/Bd2645 | bash -s v1.4.1 # pina-golada
- curl --silent --location https://goo.gl/g1CpPX | bash -s v1.3.0 # golang-dev-tools

script:
- export GO111MODULE=on
- go mod download
- go mod verify
- make test

before_deploy:
- make build

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: cAHdlHLBM4NvzRd7feWEF1ec1d1N8HpjaUc6iqGgb2uTHiwA9esP7IecosW7nLn8Y478qASPsns9pVnCnM8DvkBaaHDElhLMbO2NFTm0Mh6gGcvNpTfQcG6mVBEKawktJMMQpNVjY87UW67m/0+McRNCKk2o8nN+U8p/pHXDay80CXZj84SE8PPVST+ikiGtsxji+t11dfNJ2WS80uGGf7er3NYhojhlWgNuc+b32d/Om7synVqd2M7+oITXWkU/VRUEjT4v7uQTMhKyh5igA3TNu8nrUaJCOd44ZqXBclM25HuapPsmmCRlCs53Gfm3Bd18SHV2QHSRONUnK9hxKk5syafYK+nMghHRcjPK04AEI8KChzjXhph4oqyNOtITTBipptl0HkDLhOLP9O6TQYXjJIySbn4al6SZos++r5jyS2b4U4nqtUswAbm4SkEMp+iIpvW5BF3NIpgiVbyUqCMEjAoeMshocscmEJpcEPzkmKpdr2PlY9j+TCeh3B2tWPCl7lMwexfTqZFSN10/KdxCEHGV48PsoDgjS/Fb3RWdnMhfeD4x5RD2WR0Xo1vsE51Wl7+jSJ4mL4TspNlcGhwN4rRoB0GtsqMCPem9CKFnab+yZNjrTLNWWO1iBNNofdSBFfxZjY6hSZys1So8Y0SjT6fEQpLjNroUhoYj/Tw=
  file_glob: true
  file: binaries/*
  on:
    condition: $TRAVIS_GO_VERSION =~ ^1\.12
    tags: true
