---
name: Build and Tests

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build and Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install Tools
      run: |
        go install github.com/gordonklaus/ineffassign@latest
        go install golang.org/x/lint/golint@latest
        go install github.com/client9/misspell/cmd/misspell@latest
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go install github.com/onsi/ginkgo/ginkgo@latest

    - name: Install Dependencies
      run: |
        # Install make, curl, and javac
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update
        sudo apt-get install -y build-essential curl openjdk-8-jdk

        # Install pina-golada
        curl -fsL https://ibm.biz/Bd2645 | sudo bash -s v1.4.4

    - run: make generated-code

    - run: go build ./...
    - run: go vet ./...
    - run: ineffassign ./...
    - run: golint ./...
    - run: find . -type f | xargs misspell -source=text -error
    - run: staticcheck ./...

    - name: Run Go Unit Tests
      run: |
        ginkgo -r -randomizeAllSpecs -randomizeSuites -failOnPending -nodes=1 -compilers=1 -race -trace -cover

    - name: Upload Code Coverage Profile
      uses: codecov/codecov-action@v1
      with:
        files: ./*.coverprofile
        flags: unittests
        fail_ci_if_error: true
        verbose: false
